#!/bin/bash

LC_ALL=C
SELF="$(basename $0)"

IPV4_REGEX="([0-9]{1,3}\.){3}[0-9]{1,3}"
IPV6_REGEX="(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))"

IGNORE_PRIVATE_IP_REGEX=('^127\.' '^192\.168\.' '^172\.(1[6-9]|2[0-9]|3[01])\.' '^10\.' 'fe80:' '^::1$' )

export IPV4_REGEX IPV6_REGEX IGNORE_PRIVATE_IP_REGEX LC_ALL SELF IP_AVAILABLE IFCONFIG_AVAILABLE IP IFCONFIG OPT_SUPPRESS_PRIVATE

function join_by { local IFS="$1"; shift; echo "$*"; }

filter_out_unwanted_addresses() {

	local filter_regex="($(join_by "|" "${IGNORE_PRIVATE_IP_REGEX[@]}"))"
	grep -vE "$filter_regex"

}

usage() {

	echo
	echo "$SELF : display ipv4/ipv6 addresses of the system"
	echo
	echo "Usage: $SELF [ -p ]"
	echo
	echo "   -p	suppress private (RFC1918) addresses and ipv6 link local addresses"
	echo
	

}

script_init() {

	{
	type ip       &>/dev/null && { IP_AVAILABLE=true       ; IP="$(which ip)"	      ; }
	type ifconfig &>/dev/null && { IFCONFIG_AVAILABLE=true ; IFCONFIG="$(which ifconfig)" ; }
	[ -x /sbin/ifconfig ]     && { IFCONFIG_AVAILABLE=true ; IFCONFIG=/sbin/ifconfig      ; }
	}


	while getopts ":p" opt; do
	  case $opt in
	    p)
	      OPT_SUPPRESS_PRIVATE=true
		;;
	    h|\?)
	      usage ; exit 0
	      ;;
	    \?)
	      echo "Invalid option: -$OPTARG" >&2
	      ;;
	  esac
	done
}

get_ip_addresses() {

	[ "$IP_AVAILABLE"       == true ] && $IP addr show | grep -Eo "($IPV4_REGEX|$IPV6_REGEX)"
	[ "$IFCONFIG_AVAILABLE" == true ] && $IFCONFIG     | grep -Eo "inet6? (addr: ?)?($IPV4_REGEX|$IPV6_REGEX)" | sed -r -e 's/inet6? addr: ?//'

}

sorted_ip_addresses() {

	get_ip_addresses | sort | uniq 

}


script_init "$@"
if [ "$OPT_SUPPRESS_PRIVATE" == true ]  ; then
	sorted_ip_addresses | filter_out_unwanted_addresses
else
	sorted_ip_addresses
fi
