#!/bin/bash

#
#	check available RAM on the server and initiate maintenance if too less free memory is available
#
#	The script does nothing unless you create the file (for name see LOW_MEMORY_INFO_FILE Variable below)
#	with a number interpreted es MB size of minimum free memory required. 
#

  MAINTENANCE_SCRIPT=/usr/local/bin/xenserver-system-maintenance
LOW_MEMORY_INFO_FILE=/etc/citrix/low_memory_threshold

LC_ALL=C 

export LC_ALL MAINTENANCE_SCRIPT LOW_MEMORY_INFO_FILE

function current_free_memory {

        DATA="$(grep -E "^MemFree:" /proc/meminfo)"
        if [ -n "$DATA" ] ; then
		set $DATA

		# $2 holds free memory in kB, value should be returned in MB
		echo $(($2/1024))
	fi
}

if [ -f $LOW_MEMORY_INFO_FILE ]; then

        LOW_MEMORY=$(<$LOW_MEMORY_INFO_FILE)
        FREE_MEMORY=$(current_free_memory)

        if [ -n "$FREE_MEMORY" -a $FREE_MEMORY -lt $LOW_MEMORY ] ;then
                logger -p local7.info -t memcheck "Low memory(Free Memory: $FREE_MEMORY Threshold: $LOW_MEMORY), initiating maintenance script"
                $MAINTENANCE_SCRIPT
        fi
fi
