#!/bin/bash

#
#	citrix xenserver system maintenance script
#
#	review and adapt to your needs, maybe you do not want to 
#	throw away all old log files
#

{

# free disk space
rm -rf /var/log/*gz
find /var/patch -maxdepth 1 -type f -exec rm -v {} +
rm -rf /opt/xensource/patch-backup/*
rm -rf /var/crash/*
rm -rf /usr/share/doc

# clear the caches, linux should normally do that as memory is needed
echo 3 > /proc/sys/vm/drop_caches

# restart the XenServer Toolstack. That lockfile is used by xe-toolstack-restart
# if the lockfile is present, have a look if xe-toolstack-restart is really running
#
if [ -f /dev/shm/xe_toolstack_restart.lock ] ; then
        if pgrep /opt/xensource/bin/xe-toolstack-restart | grep -q . ; then
                echo "not using xe-toolstack-restart. an instance is running"
        else
                rm -f /dev/shm/xe_toolstack_restart.lock
                /opt/xensource/bin/xe-toolstack-restart
        fi
else
      /opt/xensource/bin/xe-toolstack-restart
fi

# The output is not that important. That's why it is 
# being written to /tmp. No tears if they're gone in
# case of a reboot

} >/tmp/system_maintenance.log

