#!/bin/bash

#
#	route_preserve
#
#	preserve a route to the current default gw for specified hosts by setting host routes for it.
#	can remove the routes too.
#
#

my_remove_route() {

        local ip="$1"
        local gw=$(/sbin/ip route show | awk -vip=$ip 'match($0,"^"ip" ") { print $3 }')

        #echo "removing route for $ip to $gw"

        if [ -n "$gw" ]; then
                /sbin/ip route delete $ip via $gw
        fi
}

my_preserve_route() {

        local defgw="$1"
        local ip="$2"
        # echo "preserving route for $ip to $defgw"

        # remove the route for this host prior to set it
        my_remove_route $ip

        /sbin/ip route add $ip/32 via $defgw
}

main() {

        local action="$1"
        local ip
        shift

        for ip in "$@" ;do
                case $action in
                        preserve) [ -n "$defgw" ] || \
                                        defgw=$(/sbin/ip route show | awk '/^default/ {print $3;exit}')
                                  my_preserve_route $defgw $ip ;;
                        remove)   my_remove_route   $ip ;;
                esac
        done
}

# --- program starts here --- 

if [ $# -lt 2 ] || [ $1 != "preserve" ] && [ $1 != "remove" ]; then
        echo 
        echo "$(basename $0): preserve/remove default route for a specific ip"
        echo
        echo "Usage: $(basename $0) preserve/remove <target-ip>"
        echo
        echo "  preserve/remove:        set a host route or remove a host route for the specific ip"
        echo
        echo "  target-ip:              ip for which default route should be removed/preserved"
        echo
        exit 1
fi

main "$@"

