#!/bin/bash

#
#	mail-watch:	watch the current postfix sending activities
#
#	Usage:		mail-watch [ -a ] [ pattern ]
#
#		-a 	process the whole log file and not continue to watch
#
#		pattern	only print lines(sender/recipient) matching the pattern (extended regex)
#
# 
# 	Sample output 
#
# Watching postfix activity for >>oops.de<<
# 
# Jul 25 16:33:09 D05C94AAE57 deferred   hen@nothing.de               christoph@oops.de                 
# Jul 25 16:33:16 1B7734AAE57 sent       jan@oops.de                  jan@oops.de                       
# Jul 25 16:33:16 1B7734AAE57 sent       jan@oops.de                  katja@blablub.de                  
# Jul 25 16:33:16 1B7734AAE57 sent       jan@oops.de                  ugur@blablub.de    
#

if [ "$1" == "-a" ]; then 
        cmd=cat
        shift
else 
        cmd="tail -n 1000 -f"
fi

echo -e "\nWatching postfix activity for >>$1<<\n"

declare -A mails

while read line ; do

        # echo $line
        set $line
        if [[ $line =~ postfix ]] ; then
                # from postfix here

                if [[ $6 =~ [0-9A-F]{9,12}: ]]; then
                        # we have a mail id in $6
                        MAIL_ID="${6%:}"

                        if [[ $7 =~ ^from= ]]; then
                                TMP="${7#*<}"
                                TMP="${TMP%>,}"
                                mails["SENDER_$MAIL_ID"]="$TMP"
                        fi

                        if [[ $7 =~ ^to= ]]; then
                                TMP="${7#*<}"
                                TMP="${TMP%>,}"
                                mails["RECIPIENT_$MAIL_ID"]="$TMP"
                        fi

                        if [[ $line =~ status= ]] ; then
                                STATE=$(grep -Eo 'status=[a-z]+' <<<"$line")
                                STATE="${STATE#status=}"
                                SENDER=${mails["SENDER_$MAIL_ID"]}
                                SENDER=${SENDER,,}
                                RECIPIENT=${mails["RECIPIENT_$MAIL_ID"]}
                                RECIPIENT=${RECIPIENT,,}
                                printf "$1 $2 $3 %s %-10s %-85s %-40s \n" "$MAIL_ID" "$STATE" "$SENDER" "$RECIPIENT"
                        fi
                fi
        fi


done < <($cmd /var/log/mail.log | grep postfix) | grep -iE "$1"

